# Generated by Django 3.2.1 on 2021-05-04 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='votes_to_Skip',
            new_name='votes_to_skip',
        ),
    ]
